source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def all
	pod 'LITLightweightStore', :path => '../'
end

target 'LITLightweightStore_Example' do
	all
end

target 'LITLightweightStore_Tests' do
	all
end
