source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LITLightweightStore_Example', :exclusive => true do
  pod 'LITLightweightStore', :path => '../'
end

target 'LITLightweightStore_Tests', :exclusive => true do
  pod 'LITLightweightStore', :path => '../'

  
end
