# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -workspace Example/LITLightweightStore.xcworkspace -scheme LITLightweightStore-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint

before_install:
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
    # 32-bit tests
    - cd Example
    - xctool -sdk iphonesimulator clean test -destination "name=iPhone 5" -find-target "LITLightweightStore_Tests"
    # 64-bit tests    
    - xctool -sdk iphonesimulator clean test -destination "name=iPhone 5s" -find-target "LITLightweightStore_Tests"

